### ISSUE TITLE
File Saving mode - Cancelling option.

### ISSUE THREAD

**Issue by TheKvc** [anic17/Newtrodit#6]
What if, i want to go back from this?? - I am forced to save the file by giving a name - we need a cancel option here. like, type "cancel" or press esc to return back to file editing ...

![image](https://github.com/anic17/Newtrodit/assets/46124093/368aa2bb-d180-46bb-980b-9c1ed322154a)

**Comment by anic17** [comment]
Hi, 
Thank you for opening a new issue.

To leave any dialog, you can press ENTER when the input is empty. Nonetheless, I feel it is a good idea to add the same functionality with ESC.

I will try to implement it soon.
Appreciate it.

**Comment by anic17** [comment]
Did some testing, the custom input function which already existed for going to a specific line (Control-G) works perfectly with any other input. Furthermore, it makes the code cleaner, and the function has many improvements over `fgets()` including:
 - It doesn't output or return a trailing newline
 - Doesn't need to redraw all the screen due to that scrolling, thus making it faster
 - It is customized, which allows better parsing of input such as a restricted character value range
 - The dialog can be left using either ENTER on an empty string (just like before) or ESC at any moment.

**Comment by ZackeryRSmith** [comment]
> Did some testing, the custom input function which already existed for going to a specific line (Control-G) works perfectly with any other input. Furthermore, it makes the code cleaner, and the function has many improvements over `fgets()` including:
> 
>     * It doesn't output or return a trailing newline
> 
>     * Doesn't need to redraw all the screen due to that scrolling, thus making it faster
> 
>     * It is customized, which allows better parsing of input such as a restricted character value range

What does this have to do with the implementation of ESC?

**Comment by anic17** [comment]
Sorry, I forgot to add the whole description. I had to leave mid-writing it. Now it seems like what I just have to do is replace every single `fgets()` with this, and I'll certainly push the changes.

**Comment by anic17** [comment]
This has been added with the new commit. Thanks for your contribution.
